### PR TITLE
Fixed bug when abstract class is initialized

### LINKED ISSUE #11: Abstract models should be omitted.
Abstract methods placed in the same folder as the rest throws an error. 

Easy fix is:
```php
    try {
	$actualModel = new $namespace;
     } catch (Throwable $e) {
           continue;
     }
```
in GenerateTypesCommand.php

Thanks!

### PR DESCRIPTION
**Pull request by Luukdewaaier**

### CODE REVIEW

**Comment by Luukdewaaier** [comment]
closes #11

File: src/Commands/GenerateTypesCommand.php [hunk 1]
```diff
@@ -136,8 +142,10 @@ private function getModels(string $directoryPath): void
             foreach (new \DirectoryIterator($directoryPath) as $file) {
                 if ($file->isDir() && !$file->isDot()) {
                     $this->getModels($file->getPathname());
-                } else if (!$file->isDot()) {
-                    $this->modelHits[] = $file->getPathname();
+                } else {
+                    if (!$file->isDot()) {
```
Comment (RicoClark) [inline src/Commands/GenerateTypesCommand.php]: dit mag wel zoals eerst?
